CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE SCHEMA IF NOT EXISTS "Events";

CREATE TABLE "Feedback" (
    "IdFeedback" text NOT NULL,
    "IdHospital" text NOT NULL,
    "ContentFeedback" text NOT NULL,
    CONSTRAINT "PK_Feedback" PRIMARY KEY ("IdFeedback")
);

CREATE TABLE "Hospital" (
    "ID" uuid NOT NULL,
    "Name" text NOT NULL,
    "ApiKey" uuid NOT NULL,
    "SiteLink" text NULL,
    CONSTRAINT "PK_Hospital" PRIMARY KEY ("ID")
);

CREATE TABLE "Ingredient" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_Ingredient" PRIMARY KEY ("Id")
);

CREATE TABLE "Events"."InventoryCheck" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "DosageInMg" integer NOT NULL,
    "TimeStamp" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_InventoryCheck" PRIMARY KEY ("Id")
);

CREATE TABLE "Medicine" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Description" text NULL,
    "DosageInMilligrams" integer NOT NULL,
    "Manufacturer" text NULL,
    "SideEffects" text[] NOT NULL,
    "PossibleReactions" text[] NOT NULL,
    "WayOfConsumption" text NOT NULL,
    "PotentialDangers" text NULL,
    CONSTRAINT "PK_Medicine" PRIMARY KEY ("Id")
);

CREATE TABLE "MedicineInventory" (
    "MedicineId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_MedicineInventory" PRIMARY KEY ("MedicineId")
);

CREATE TABLE "User" (
    "UserId" uuid NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "Username" character varying(20) NOT NULL,
    "Password" text NOT NULL,
    "Role" integer NOT NULL,
    "IsLogicalDeleted" boolean NOT NULL,
    "IsBlocked" boolean NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("UserId")
);

CREATE TABLE "IngredientMedicine" (
    "IngredientsId" integer NOT NULL,
    "MedicinesId" integer NOT NULL,
    CONSTRAINT "PK_IngredientMedicine" PRIMARY KEY ("IngredientsId", "MedicinesId"),
    CONSTRAINT "FK_IngredientMedicine_Ingredient_IngredientsId" FOREIGN KEY ("IngredientsId") REFERENCES "Ingredient" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IngredientMedicine_Medicine_MedicinesId" FOREIGN KEY ("MedicinesId") REFERENCES "Medicine" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MedicineCombination" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstMedicineId" integer NOT NULL,
    "SecondMedicineId" integer NOT NULL,
    CONSTRAINT "PK_MedicineCombination" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MedicineCombination_Medicine_FirstMedicineId" FOREIGN KEY ("FirstMedicineId") REFERENCES "Medicine" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MedicineCombination_Medicine_SecondMedicineId" FOREIGN KEY ("SecondMedicineId") REFERENCES "Medicine" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Order" (
    "Order_Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NULL,
    "OrderDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Order" PRIMARY KEY ("Order_Id"),
    CONSTRAINT "FK_Order_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("UserId") ON DELETE RESTRICT
);

CREATE TABLE "OrderItem" (
    "OrderItemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "MedicineId" integer NULL,
    "Quantity" integer NOT NULL,
    "Order_Id" integer NULL,
    CONSTRAINT "PK_OrderItem" PRIMARY KEY ("OrderItemId"),
    CONSTRAINT "FK_OrderItem_Medicine_MedicineId" FOREIGN KEY ("MedicineId") REFERENCES "Medicine" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrderItem_Order_Order_Id" FOREIGN KEY ("Order_Id") REFERENCES "Order" ("Order_Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_Hospital_ApiKey" ON "Hospital" ("ApiKey");

CREATE UNIQUE INDEX "IX_Ingredient_Name" ON "Ingredient" ("Name");

CREATE INDEX "IX_IngredientMedicine_MedicinesId" ON "IngredientMedicine" ("MedicinesId");

CREATE INDEX "IX_MedicineCombination_FirstMedicineId" ON "MedicineCombination" ("FirstMedicineId");

CREATE INDEX "IX_MedicineCombination_SecondMedicineId" ON "MedicineCombination" ("SecondMedicineId");

CREATE INDEX "IX_Order_UserId" ON "Order" ("UserId");

CREATE INDEX "IX_OrderItem_MedicineId" ON "OrderItem" ("MedicineId");

CREATE INDEX "IX_OrderItem_Order_Id" ON "OrderItem" ("Order_Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220108033718_first', '5.0.11');

COMMIT;

